parameters:
- name: RunUnitTestsOnWindows
  displayName: Run unit tests on Windows
  type: boolean
  default: true
- name: RunFunctionalTestsOnWindows
  displayName: Run functional tests on Windows
  type: boolean
  default: true
- name: RunUnitTestsOnLinux
  displayName: Run unit tests on Linux
  type: boolean
  default: false
- name: RunFunctionalTestsOnLinux
  displayName: Run functional tests on Linux
  type: boolean
  default: false
- name: RunUnitTestsOnMacOS
  displayName: Run unit tests on MacOS
  type: boolean
  default: false
- name: RunFunctionalTestsOnMacOS
  displayName: Run functional tests on MacOS
  type: boolean
  default: false
- name: RunSourceBuild
  displayName: Run a SourceBuild build
  type: boolean
  default: false
- name: RunStaticAnalysis
  displayName: Run a static analysis
  type: boolean
  default: false
variables:
  DOTNET_NOLOGO: 1
  NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY: 3,1000
  SkipSigning: true
  CI: true
  Codeql.Enabled: false


stages:
- ${{ if eq(parameters.RunUnitTestsOnWindows, true) }}:
  - stage:
    displayName: Unit Tests on Windows (.NET Framework 4.7.2)
    dependsOn: []
    jobs:
    - template: pr.job.yml
      parameters:
        displayName: Unit Tests on Windows (.NET Framework 4.7.2)
        osName: Windows
        agentPool: Azure Pipelines
        vmImage: windows-latest
        testType: Unit
        testTargetFramework: net472

- ${{ if eq(parameters.RunUnitTestsOnWindows, true) }}:
  - stage:
    displayName: Unit Tests on Windows (.NET 10.0)
    dependsOn: []
    jobs:
    - template: pr.job.yml
      parameters:
        displayName: Unit Tests on Windows (.NET 10.0)
        osName: Windows
        agentPool: Azure Pipelines
        vmImage: windows-latest
        testType: Unit
        testTargetFramework: net10.0

- ${{ if eq(parameters.RunFunctionalTestsOnWindows, true) }}:
  - stage:
    displayName: Msbuild.Integration.Test on Windows (.NET Framework 4.7.2)
    dependsOn: []
    jobs:
    - template: pr.job.yml
      parameters:
        displayName: Msbuild.Integration.Test on Windows (.NET Framework 4.7.2)
        osName: Windows
        agentPool: Azure Pipelines
        vmImage: windows-latest
        testType: Functional
        testTargetFramework: net472
        testProjectName: Msbuild.Integration.Test

- ${{ if eq(parameters.RunFunctionalTestsOnWindows, true) }}:
  - stage:
    displayName: NuGet.CommandLine.FuncTest on Windows (.NET Framework 4.7.2)
    dependsOn: []
    jobs:
    - template: pr.job.yml
      parameters:
        displayName: NuGet.CommandLine.FuncTest on Windows (.NET Framework 4.7.2)
        osName: Windows
        agentPool: Azure Pipelines
        vmImage: windows-latest
        testType: Functional
        testTargetFramework: net472
        testProjectName: NuGet.CommandLine.FuncTest
        timeoutInMinutes: 30

- ${{ if eq(parameters.RunFunctionalTestsOnWindows, true) }}:
  - stage:
    displayName: NuGet.CommandLine.Test on Windows (.NET Framework 4.7.2)
    dependsOn: []
    jobs:
    - template: pr.job.yml
      parameters:
        displayName: NuGet.CommandLine.Test on Windows (.NET Framework 4.7.2)
        osName: Windows
        agentPool: Azure Pipelines
        vmImage: windows-latest
        testType: Functional
        testTargetFramework: net472
        testProjectName: NuGet.CommandLine.Test
        testVerbosity: normal
        timeoutInMinutes: 45

- ${{ if eq(parameters.RunFunctionalTestsOnWindows, true) }}:
  - stage:
    displayName: NuGet.Packaging.FuncTest on Windows (.NET Framework 4.7.2)
    dependsOn: []
    jobs:
    - template: pr.job.yml
      parameters:
        displayName: NuGet.Packaging.FuncTest on Windows (.NET Framework 4.7.2)
        osName: Windows
        agentPool: Azure Pipelines
        vmImage: windows-latest
        testType: Functional
        testTargetFramework: net472
        testProjectName: NuGet.Packaging.FuncTest

- ${{ if eq(parameters.RunFunctionalTestsOnWindows, true) }}:
  - stage:
    displayName: Dotnet.Integration.Test on Windows (.NET 10.0)
    dependsOn: []
    jobs:
    - template: pr.job.yml
      parameters:
        displayName: Dotnet.Integration.Test on Windows (.NET 10.0)
        osName: Windows
        agentPool: Azure Pipelines
        vmImage: windows-latest
        testType: Functional
        testTargetFramework: net10.0
        testProjectName: Dotnet.Integration.Test
        timeoutInMinutes: 60

- ${{ if eq(parameters.RunFunctionalTestsOnWindows, true) }}:
  - stage:
    displayName: NuGet.Packaging.FuncTest on Windows (.NET 10.0)
    dependsOn: []
    jobs:
    - template: pr.job.yml
      parameters:
        displayName: NuGet.Packaging.FuncTest on Windows (.NET 10.0)
        osName: Windows
        agentPool: Azure Pipelines
        vmImage: windows-latest
        testType: Functional
        testTargetFramework: net10.0
        testProjectName: NuGet.Packaging.FuncTest

